### ISSUE TITLE
催更支持Deepin23的新任务栏

### ISSUE THREAD

**Issue by Re-s** [zty199/dde-dock-switch_graphics_card#2]
插件无法在v23的dde-shell上正常显示，以及AMD+NVIDIA独显的组合

**Comment by zty199** [comment]
https://github.com/zty199/dde-dock-switch_graphics_card/releases/tag/2.0.1

写了，为了适配 RC 上的 dde-shell 换成 Qt6 编译了；据大佬说后面会提供兼容方案，插件可以继续用 Qt5 编译即可，估计 V23 正式版还要再适配一次吧。

---

至于 AMD 嘛......先咕了，没有这种机器也不敢随便改（自动换成 3A 平台的笔记本之后就没咋改过了......）
