### ISSUE TITLE
v23最新内测版本无法使用

### ISSUE THREAD

**Issue by minilulubai** [zty199/dde-dock-switch_graphics_card#3]
目前最新的deepin v23内测版本,无法使用. 右键应用图标有“使用prime-run运行”.

但任务栏不显示插件、控制中心——个性化——桌面——插件区域不显示此插件.

等v23定型后, 希望再更新.谢谢.

**Comment by zty199** [comment]
[https://github.com/zty199/dde-dock-switch_graphics_card/releases/tag/2.0.2](https://github.com/zty199/dde-dock-switch_graphics_card/releases/tag/2.0.2)
上周末偷偷更新过了；不过应用商店里暂时不会传新版本，等 V23 正式发布了再更新
